Repository YPrahasith/dsc-web, pull requests merged in 2020-10, with the labels that each got.

#1 Added login and register routes to backend
  .gitignore
  README.md
  client/package.json
  client/src/index.js
  server/app.js
  server/config/config.json
  server/docker-compose.yml
  server/migrations/20201017202221-createUserTable.js
  server/models/User.js
  server/package-lock.json
  server/package.json
  server/routes/api.js
  server/routes/auth/authRoute.js
  server/routes/auth/index.js
  server/utils/db_connection.js
  server/utils/validators.js
Labels: Priority: High, Status: In Progress, Type: Feature, enhancement

#2 team page basic layout
  views/assets/css/team.css
  views/assets/img/face.jpg
  views/assets/img/team.png
  views/team.html
Labels: Priority: Medium, Status: In Progress, Type: Feature, enhancement, hacktoberfest-accepted

#4 flip-able cards, staff card fixed
  views/assets/css/team.css
  views/assets/js/team.js
  views/team.html
Labels: Priority: Low, Status: PR Welcome, Type: Maintenance, enhancement, hacktoberfest-accepted

#5 Added router and finished navbar
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/public/manifest.json
  client/src/App.css
  client/src/App.js
  client/src/components/Navbar.js
  client/src/components/styles/Navbar.css
  client/src/index.css
  client/src/index.js
  package-lock.json
Labels: Priority: Medium, Status: PR Welcome, Type: Feature, enhancement, hacktoberfest-accepted

#10 client: fixed styling for the navbar
  client/components/nav.js
  client/public/css/index.css
Labels: Priority: Low, Status: PR Welcome, Type: Bug, bug, hacktoberfest-accepted

#11 views: Team
  views/assets/css/team.css
  views/assets/js/team.js
  views/team.html
Labels: Priority: Medium, Status: PR Welcome, Type: Refactoring, hacktoberfest-accepted

#26 client: Image, Home page
  client/components/EventTimelineItem.js
  client/components/TeamBigCard.js
  client/components/TeamCard.js
  client/components/nav.js
  client/components/sidebar.js
  client/data/eventData.js
  client/pages/blog.js
  client/pages/events.js
  client/pages/index.js
  client/pages/projects.js
  client/pages/resources.js
  client/pages/team.js
  client/pages/team2019.js
  client/public/css/projects.css
  client/public/css/team.css
Labels: Priority: Medium, Status: PR Welcome, Type: Maintenance, hacktoberfest-accepted

#27 client: Fixed header image bug on theme switch and added a small loading bar
  client/components/layout.js
  client/components/themeMode.js
  client/contexts/ThemeContext.js
  client/package-lock.json
  client/package.json
  client/pages/_app.js
  client/pages/events.js
  client/pages/index.js
  client/public/css/events.css
  client/public/css/loading.css
  client/public/sw.js
Labels: Priority: Medium, Status: Need More Info, Type: Bug

#29 client: Project Material UI cards
  client/components/ProjectCard.js
  client/data/projectData.js
  client/package-lock.json
  client/pages/projects.js
  client/public/css/projects.css
  client/public/images/jssstucse.jpg
Labels: Priority: Medium, Status: PR Welcome, Type: Refactoring, hacktoberfest-accepted
